######################################################################
# Automatically generated by qmake (3.1) Mon Feb 6 22:47:43 2017
######################################################################

TEMPLATE = app
TARGET = Code
INCLUDEPATH += .
QT += core gui widgets

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp Project1.cpp
