######################################################################
# Automatically generated by qmake (3.0) Tue Feb 7 12:02:43 2017
######################################################################

TEMPLATE = app
TARGET = Code
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += mainwindow.h ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp Project1.cpp
