######################################################################
# Automatically generated by qmake (3.1) Sun Feb 12 22:20:24 2017
######################################################################

TEMPLATE = app
TARGET = mac
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += mainwindow.h ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp Project1.cpp
