######################################################################
# Automatically generated by qmake (3.1) Fri Feb 24 12:08:25 2017
######################################################################

TEMPLATE = app
TARGET = mac
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp Project1.cpp
QT += widgets
