######################################################################
# Automatically generated by qmake (3.0) Sun Jan 29 23:27:40 2017
######################################################################

TEMPLATE = app
TARGET = Code
INCLUDEPATH += .
QT+=widgets
# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp Project1.cpp
