######################################################################
# Automatically generated by qmake (3.1) Fri Feb 24 12:05:43 2017
######################################################################

TEMPLATE = app
TARGET = mac
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h Matrix.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp Matrix.cpp Project2.cpp
QT += widgets
