######################################################################
# Automatically generated by qmake (3.1) Fri Feb 24 23:56:23 2017
######################################################################

TEMPLATE = app
TARGET = mac
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h Matrix.h ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp Matrix.cpp Project2.cpp
QT += widgets
