######################################################################
# Automatically generated by qmake (3.1) Fri Mar 10 19:52:08 2017
######################################################################

TEMPLATE = app
TARGET = mac
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp Project4.cpp
QT += widgets
